name: push ecr  # 이름설정

on:  # bracnch main push 감지 시 실행
  push:
    branches: [ main ]

jobs:
  build:   
    name: Build Image
    runs-on: ubuntu-latest # ubuntu에서 실행

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2 #checkout action 사용
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2 # ecr이 위치하는 리전

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr-test # !!!!!!!본인의 ecr로 변경 필요!!!!!!!!
#        IMAGE_TAG: latest
      run: | # 도커 파일 빌드 후 푸쉬
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
